server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:

        - id: second2
          uri: lb://fc-catalog-service
          predicates:
            - Path=/second/**
          filters:
            - StripPrefix=1

        - id: uber-driver-service
          uri: lb://uber-driver-service
          predicates:
            - Path=/driver/**
          filters:
            - StripPrefix=1


        - id: uber-user-service
          uri: lb://uber-user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true
