server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:

        - id: uber-driver-service
          uri: lb://uber-driver-service
          predicates:
            - Path=/driver/**
          filters:
            - RewritePath=driver/(?<path>.*), /$\{path}


        - id: uber-user-service
          uri: lb://uber-user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=user/(?<path>.*), /$\{path}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true



springdoc:
  swagger-ui:
    urls:
      - name: driver
        url: /driver/v3/api-docs
      - name: user
        url: /user/v3/api-docs
     
